name: describe-docker
description: GitHub action to update docker description
inputs:
  docker_username:
    description: Docker hub username
    required: true
  docker_password:
    description: Docker hub password
    required: true
  docker_registry:
    description: Docker hub registry URL
    required: false
    default: https://hub.docker.com/v2
  repository_name:
    description: Name of the docker image repository
    required: true
  summary:
    description: Docker repository overview (character limit enforced)
    required: true
  description_file:
    description: Filename to read the full description for the docker image.
    required: true
  summary_limit:
    description: Summary limit for docker hub overview (defaults to 100 for hub.docker.com)
    required: false
    default: "100"
outputs: { }
runs:
  using: composite
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Validate Inputs
      run: |
        if [[ -z "${{ inputs.docker_username }}" ]]; then
          echo "::error title=MissingInput::Docker hub username is not provided."
          exit 1
        fi

        if [[ -z "${{ inputs.docker_password }}" ]]; then
          echo "::error title=MissingInput::Docker hub password is not provided."
          exit 1
        fi

        if [[ -z "${{ inputs.docker_registry }}" ]]; then
          echo "::error title=MissingInput::Docker registry URL is not provided."
          exit 1
        fi

        if [[ -z "${{ inputs.repository_name }}" ]]; then
          echo "::error title=MissingInput::Repository name is not provided."
          exit 1
        fi

        if [[ -z "${{ inputs.summary }}" ]]; then
          echo "::warning title=MissingInput::Summary is not provided."
        fi

        if [[ -z "${{ inputs.description_file }}" ]]; then
          echo "::error title=MissingInput::Description file is not provided."
          exit 1
        fi

        if [[ ! -f "${{ inputs.description_file }}" ]]; then
          echo "::error title=MissingInput::Description file '${{ inputs.description_file }}' does not exist."
          exit 1
        fi

        if [[ "${{ inputs.repository_name }}" == "${{ inputs.docker_username }}/"* ]]; then
            echo "REPOSITORY_NAME=${{ inputs.repository_name }}" >> $GITHUB_ENV
        else
            echo "REPOSITORY_NAME=${{ inputs.docker_username }}/${{ inputs.repository_name }}" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Fetch API Token
      run: |
        payload=$(jq -n \
          --arg username "${{ inputs.docker_username }}" \
          --arg password "${{ inputs.docker_password }}" \
          '{username: $username, password: $password}')

        token=$(curl -s -X POST "${{ inputs.docker_registry }}/users/login/" \
          -H "Content-Type: application/json" \
          -d "$payload" | jq -r '.token')

        if [[ -n "${token}" ]]; then
          echo "::debug title=Token Retriever::Retrieved token successfully"
          echo "API_TOKEN=${token}" >> $GITHUB_ENV
        else
          echo "::error title=Token Retriever::Failed to get auth token"
          exit 1
        fi
      shell: bash

    - name: Check summary limit
      run: |
        warn="Summary exceeds DockerHub's limit and has been truncated to ${{ inputs.summary_limit }} characters."
        summary="${{ inputs.summary }}"
        summary_length=${#summary}
        if [[ "$summary_length" -gt "${{ inputs.summary_limit }}" ]]; then
          echo "::warning title=Summary Too Long::${warn}"
          echo "SUMMARY=${summary:0:97}..." >> $GITHUB_ENV
        else
          echo "SUMMARY=${summary}" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Update description
      run: |
        full_description="$(cat "${{ inputs.description_file }}")"
        payload=$(jq -n \
          --arg description "${{ env.SUMMARY }}" \
          --arg full_description "$full_description" \
          '{description: $description, full_description: $full_description}')

        response=$(curl -s -o /tmp/desc -w "%{http_code}" -X PATCH \
          "${{ inputs.docker_registry }}/repositories/${{ env.REPOSITORY_NAME }}/" \
          -H "Authorization: Bearer ${{ env.API_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d "$payload")

        status_code="${response: -3}"
        if [[ "${status_code}" -eq 200 ]]; then
          echo "::notice title=Updater::Updated description successfully"
          exit 0
        elif [[ -f "/tmp/desc" ]]; then
          echo "::error title=Updater::Failed to update description"
          response_payload="$(cat /tmp/desc)"
          reason=$(echo "${response_payload}" | jq '.message')
          info=$(echo "${response_payload}" | jq '.errinfo')
          if [[ "$reason" != "null" ]]; then
            echo "::error title=Updater::[${status_code}]: $reason"
          else
            echo "::error title=Updater::[${status_code}]: $(cat /tmp/desc)"
          fi
          if [[ "$info" != "null" ]]; then
            echo "::error title=Updater::${info}"
          fi
        else
          echo "::error title=Updater::Failed to update description - ${status_code}"
        fi
        exit 1
      shell: bash
